9j0d2p achivement api
BuildSchool-FETeam/schoolX-graphQL pull request #35
Opened 2021-10-16 13:28 UTC by quangtho908

Hú hú

2021-10-17 13:46 UTC, phanhuutoan requested changes

2021-10-17 13:46 UTC, phanhuutoan commented on src/clientUser/services/achievement.service.ts
> +    }else {
cài prettier vào bạn ơi

2021-10-17 13:46 UTC, phanhuutoan commented on src/clientUser/services/achievement.service.ts
> +      if(checkAvaiable.length !== 0) return false;
cài eslint nữa đi bạn ơi

2021-10-17 15:10 UTC, phanhuutoan requested changes
Viết code thông minh, optimize đầy đủ, nhưng cần phải chỉnh 1 số chỗ nữa, push lên a manual test lại

2021-10-17 15:10 UTC, phanhuutoan commented on src/clientUser/services/achievement.service.ts
> +    const checkAvaiable = _.filter(followedMe, ['id', userFollowedMe.id]);
cái này dùng `findIndex ` được rồi `filter ` nó phải work nhiều hơn, nếu e chỉ muốn check là nó có tồn tại hay ko, thậm chí là dùng `_.some()` nếu quen tay hơn

2021-10-17 15:10 UTC, phanhuutoan commented on src/clientUser/services/achievement.service.ts
> +    const completedCourse = !existedAchi.completedCourses ? [] : existedAchi.completedCourses;
Để tránh các vấn đề về bug reference tốt nhất e nên sd `_.clone(existedAchi.completedCourses)` nếu giải quyết theo kiểu immutable ntn. 

=> ngoài ra cũng sửa tương tự cho mấy cái trước

2021-10-17 15:12 UTC, phanhuutoan commented on src/clientUser/services/achievement.service.ts
> +    const checkAvaiable = _.filter(newCourses, ['id', course.id]);
Cài hộ a cái spell check trong vscode nữa Thọ :V 
=> available

2021-10-17 15:13 UTC, quangtho908 commented on src/clientUser/services/achievement.service.ts
> +    }else {
Cái này nó chịu thua luôn rồi -_-

2021-10-17 15:16 UTC, quangtho908 commented on src/courses/services/course.service.ts
> +
Nhưng mà ở ngoài thì sao check available được

2021-10-18 01:09 UTC, phanhuutoan requested changes

2021-10-18 01:09 UTC, phanhuutoan commented on src/courses/services/course.service.ts
>      }
A đề xuất thuật toán chỗ này, e có thể cách ra làm 2 hàm (và gộp vào cũng được) và truyền vào như sau 
`addJoinedUser(clientUser: ClientUser)` => dùng để add joined user
`removeJoinedUser(clientUser: ClientUser)` => dùng để remove joined user

Bởi vì nếu bên achievement đã có thể add/remove được hoặc return true rồi thì bên này chắc chắn cũng có thể add user vào được, e không cần check available ở đây nữa. Tối giản logic ở đây lại

2021-10-18 06:40 UTC, merged